# file: Makefile
# author: 2018117610_moonjunyong
# datetime: 2021-10-23(updated) 15:30
# description : compile in ls2.c myls2.c

# build all
all: ls2 myls

# build ls2
ls2: ls2.o
	cc ls2.c -o ls2

# build myls
myls: myls.o
	cc myls.c -o myls

# build clean
clean: 
	rm -rf *.o	

