#file: Makefile
#author: 2018117610_moonjunyong
#datetime: 2021-11-12 11:00

#build all
all: waitdemo2 waitdemo3

#build waitdemo2
waitdemo2: waitdemo2.o
		cc waitdemo2.c -o waitdemo2

#build waitdemo3
waitdemo3: waitdemo3.o
		cc waitdemo3.c -o waitdemo3

# build clean
clean:
	rm -rf ./*.o
