#Makefile
#2018117610 moon jun yong
#datetime: 2021-10-14 22:30

app.out: play_again1 play_again2 play_again3 play_again4

play_again1: play_again1.o
		gcc play_again1.c -o play_again1
play_again2: play_again2.o
		gcc play_again2.c -o play_again2
play_again3: play_again3.o
		gcc play_again3.c -o play_again3
play_again4: play_again4.o
		gcc play_again4.c -o play_again4
